version: '3.8'

services:
  app:
    build:
      context: /opt/gym_system
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - /opt/gym_system/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
  driver:
