version: '3.5'

services:
  app:
    image: node:14
    container_name: app_gym
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - node_studant:/appGym/src/studant
      - node_trainer:/appGym/src/trainer
      - node_types:/appGym/src/types

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gymdb
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - gym_mysql:/var/lib/mysql

  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu_gym
    restart: unless-stopped
    command: sleep infinity
    volumes:
      - node_studant:/appGym/src/studant
      - node_trainer:/appGym/src/trainer
      - node_types:/appGym/src/types
      - gym_mysql:/var/lib/mysql

volumes:
  node_studant:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/gym_system/src/studant
  node_trainer:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/gym_system/src/trainer
  node_types:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/gym_system/src/types
  gym_mysql:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/gym_system/db
