name: build and push docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image (optional)'
        required: false
        type: string
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.1

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            gmartins882/gymsystem:latest
            ${{ inputs.tag != '' && format('gmartins882/gymsystem:{0}', inputs.tag) || '' }}
